spring:
  application:
    name: SauRestBoot
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:sau_rest_2023}
    username: ${DB_USERNAME:admin}
    password: ${DB_USERNAME:admin}
server:
  port: ${SAU_PORT:0}
  forward-headers-strategy: framework
dashboard:
  limit: 600
sql:
  parameters:
    parameterset:
      limit: 500
      protect: false
      interval: 00:00:09
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka